// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mem,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=129,HLS_SYN_DSP=0,HLS_SYN_FF=326,HLS_SYN_LUT=516,HLS_VERSION=2018_3}" *)

module mem (
        ap_clk,
        ap_rst_n,
        s_axi_CRTL_BUS_AWVALID,
        s_axi_CRTL_BUS_AWREADY,
        s_axi_CRTL_BUS_AWADDR,
        s_axi_CRTL_BUS_WVALID,
        s_axi_CRTL_BUS_WREADY,
        s_axi_CRTL_BUS_WDATA,
        s_axi_CRTL_BUS_WSTRB,
        s_axi_CRTL_BUS_ARVALID,
        s_axi_CRTL_BUS_ARREADY,
        s_axi_CRTL_BUS_ARADDR,
        s_axi_CRTL_BUS_RVALID,
        s_axi_CRTL_BUS_RREADY,
        s_axi_CRTL_BUS_RDATA,
        s_axi_CRTL_BUS_RRESP,
        s_axi_CRTL_BUS_BVALID,
        s_axi_CRTL_BUS_BREADY,
        s_axi_CRTL_BUS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;
parameter    C_S_AXI_CRTL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CRTL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CRTL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_CRTL_BUS_AWVALID;
output   s_axi_CRTL_BUS_AWREADY;
input  [C_S_AXI_CRTL_BUS_ADDR_WIDTH - 1:0] s_axi_CRTL_BUS_AWADDR;
input   s_axi_CRTL_BUS_WVALID;
output   s_axi_CRTL_BUS_WREADY;
input  [C_S_AXI_CRTL_BUS_DATA_WIDTH - 1:0] s_axi_CRTL_BUS_WDATA;
input  [C_S_AXI_CRTL_BUS_WSTRB_WIDTH - 1:0] s_axi_CRTL_BUS_WSTRB;
input   s_axi_CRTL_BUS_ARVALID;
output   s_axi_CRTL_BUS_ARREADY;
input  [C_S_AXI_CRTL_BUS_ADDR_WIDTH - 1:0] s_axi_CRTL_BUS_ARADDR;
output   s_axi_CRTL_BUS_RVALID;
input   s_axi_CRTL_BUS_RREADY;
output  [C_S_AXI_CRTL_BUS_DATA_WIDTH - 1:0] s_axi_CRTL_BUS_RDATA;
output  [1:0] s_axi_CRTL_BUS_RRESP;
output   s_axi_CRTL_BUS_BVALID;
input   s_axi_CRTL_BUS_BREADY;
output  [1:0] s_axi_CRTL_BUS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] a;
wire   [31:0] ma;
wire   [31:0] data_i;
reg   [31:0] data_o;
reg    data_o_ap_vld;
wire   [31:0] flag;
reg   [15:0] nvm_address0;
reg    nvm_ce0;
reg    nvm_we0;
wire   [31:0] nvm_q0;
reg   [5:0] dram_address0;
reg    dram_ce0;
reg    dram_we0;
wire   [31:0] dram_q0;
reg   [63:0] a_read_reg_167;
wire   [0:0] tmp_fu_132_p1;
reg   [0:0] tmp_reg_172;
wire   [0:0] tmp_1_fu_136_p3;
reg   [0:0] tmp_1_reg_176;
wire  signed [63:0] tmp_6_fu_144_p1;
wire  signed [63:0] tmp_7_fu_149_p1;
wire  signed [63:0] tmp_8_fu_154_p1;
wire    ap_CS_fsm_state2;
wire   [31:0] storemerge_fu_159_p3;
wire  signed [31:0] tmp_6_fu_144_p0;
wire  signed [31:0] tmp_7_fu_149_p0;
wire  signed [31:0] tmp_8_fu_154_p0;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

mem_nvm #(
    .DataWidth( 32 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
nvm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(nvm_address0),
    .ce0(nvm_ce0),
    .we0(nvm_we0),
    .d0(dram_q0),
    .q0(nvm_q0)
);

mem_dram #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
dram_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(dram_address0),
    .ce0(dram_ce0),
    .we0(dram_we0),
    .d0(data_i),
    .q0(dram_q0)
);

mem_CRTL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CRTL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CRTL_BUS_DATA_WIDTH ))
mem_CRTL_BUS_s_axi_U(
    .AWVALID(s_axi_CRTL_BUS_AWVALID),
    .AWREADY(s_axi_CRTL_BUS_AWREADY),
    .AWADDR(s_axi_CRTL_BUS_AWADDR),
    .WVALID(s_axi_CRTL_BUS_WVALID),
    .WREADY(s_axi_CRTL_BUS_WREADY),
    .WDATA(s_axi_CRTL_BUS_WDATA),
    .WSTRB(s_axi_CRTL_BUS_WSTRB),
    .ARVALID(s_axi_CRTL_BUS_ARVALID),
    .ARREADY(s_axi_CRTL_BUS_ARREADY),
    .ARADDR(s_axi_CRTL_BUS_ARADDR),
    .RVALID(s_axi_CRTL_BUS_RVALID),
    .RREADY(s_axi_CRTL_BUS_RREADY),
    .RDATA(s_axi_CRTL_BUS_RDATA),
    .RRESP(s_axi_CRTL_BUS_RRESP),
    .BVALID(s_axi_CRTL_BUS_BVALID),
    .BREADY(s_axi_CRTL_BUS_BREADY),
    .BRESP(s_axi_CRTL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .a(a),
    .ma(ma),
    .data_o(data_o),
    .data_o_ap_vld(data_o_ap_vld),
    .data_i(data_i),
    .flag(flag)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        a_read_reg_167 <= a;
        tmp_1_reg_176 <= flag[32'd1];
        tmp_reg_172 <= tmp_fu_132_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_172 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_o = storemerge_fu_159_p3;
    end else begin
        data_o = data_i;
    end
end

always @ (*) begin
    if (((tmp_reg_172 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_o_ap_vld = 1'b1;
    end else begin
        data_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        if ((tmp_fu_132_p1 == 1'd1)) begin
            dram_address0 = tmp_8_fu_154_p1;
        end else if (((tmp_1_fu_136_p3 == 1'd1) & (tmp_fu_132_p1 == 1'd0))) begin
            dram_address0 = tmp_7_fu_149_p1;
        end else if (((tmp_1_fu_136_p3 == 1'd0) & (tmp_fu_132_p1 == 1'd0))) begin
            dram_address0 = tmp_6_fu_144_p1;
        end else begin
            dram_address0 = 'bx;
        end
    end else begin
        dram_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b1) & (tmp_1_fu_136_p3 == 1'd0) & (tmp_fu_132_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (tmp_1_fu_136_p3 == 1'd1) & (tmp_fu_132_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1)) | ((ap_start == 1'b1) & (tmp_fu_132_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state1)))) begin
        dram_ce0 = 1'b1;
    end else begin
        dram_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (tmp_1_fu_136_p3 == 1'd1) & (tmp_fu_132_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        dram_we0 = 1'b1;
    end else begin
        dram_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        nvm_address0 = a_read_reg_167;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        nvm_address0 = a;
    end else begin
        nvm_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        nvm_ce0 = 1'b1;
    end else begin
        nvm_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_1_reg_176 == 1'd0) & (tmp_reg_172 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        nvm_we0 = 1'b1;
    end else begin
        nvm_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign storemerge_fu_159_p3 = ((tmp_1_reg_176[0:0] === 1'b1) ? dram_q0 : nvm_q0);

assign tmp_1_fu_136_p3 = flag[32'd1];

assign tmp_6_fu_144_p0 = ma;

assign tmp_6_fu_144_p1 = tmp_6_fu_144_p0;

assign tmp_7_fu_149_p0 = ma;

assign tmp_7_fu_149_p1 = tmp_7_fu_149_p0;

assign tmp_8_fu_154_p0 = ma;

assign tmp_8_fu_154_p1 = tmp_8_fu_154_p0;

assign tmp_fu_132_p1 = flag[0:0];

endmodule //mem
